In [1]:
!pip install gym

    100% |████████████████████████████████| 1.5MB 10.3MB/s 
    100% |████████████████████████████████| 1.0MB 12.5MB/s 
  Running setup.py bdist_wheel for gym ... - \ | / done
  Stored in directory: /root/.cache/pip/wheels/ea/ec/dd/33bcc8801d345f0b640fced8a0864a7c8474828564bc5ccf70
Successfully built gym


In [0]:
import numpy as np
import gym
import random

In [0]:
env = gym.make("FrozenLake-v0")

In [4]:
action_size=env.action_space.n
state_size=env.observation_space.n

print(state_size,action_size)

16 4


In [5]:
qtable=np.zeros((state_size,action_size))
qtable

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Initialize the parameters:

In [0]:
total_episodes=25000
learning_rate=0.8
max_steps=99
gamma=0.90 # Discounting rate

In [0]:
epsilon=1 # Exploraton rate
max_epsilon=1
min_epsilon=0.01
decay_rate=0.01 # Exponential decay rate for exploration prob

# The Q learning algirithm:

In [8]:
rewards=[]
for episode in range(total_episodes):
  state=env.reset()
  step=0
  done=False
  total_rewards=0
  
  for step in range(max_steps):
    exp_exp_tradeoff=random.uniform(0,1)
    if exp_exp_tradeoff>epsilon:
      action=np.argmax(qtable[state,:])
    else:
      action=env.action_space.sample()
    
    new_state,reward,done,info=env.step(action)
    
    qtable[state,action]+=learning_rate*(reward+gamma*(np.max(qtable[new_state,:]))-qtable[state,action]) # Updating Q table values 
    
    total_rewards+=reward
    state=new_state
    
    if done==True:
      break
      
  epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
  rewards.append(total_rewards)
  
print("score over time : "+str(sum(rewards)/total_episodes))
print(qtable)

score over time : 0.43056
[[2.04625914e-01 6.61707634e-03 4.56550851e-03 6.44876654e-03]
 [4.39868768e-04 6.83178283e-04 8.87671849e-04 6.20149870e-02]
 [8.82116565e-04 1.92783963e-04 1.52232352e-03 1.38178052e-03]
 [5.37903907e-04 1.01523335e-03 2.72975565e-04 1.34573144e-03]
 [3.83860660e-01 1.70639950e-03 2.00305714e-03 5.80477373e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.75885767e-02 1.72654619e-06 1.26452659e-05 1.23767989e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.30372922e-03 2.44909063e-03 3.19514149e-03 6.28635001e-01]
 [7.75062098e-04 4.32719392e-01 3.43991518e-04 2.84421763e-02]
 [1.51406499e-01 8.30550215e-04 1.73247403e-03 1.80453917e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.60547422e-02 8.23514746e-05 8.81794864e-01 2.99026581e-02]
 [1.00191956e-01 9.98522270e-01 1.05516388e-01 7.37748564e-02]
 [0.00000000e+00 0.00000000e+

In [60]:
for episode in range(10):
  state=env.reset()
  step=0
  done=False
  print("****************************************************")
  print("EPISODE ", episode)
  for step in range(max_steps):
    action=np.argmax(qtable[state,:])
    new_state,reward,done,info=env.step(action)
    if done:
      env.render()
      print("number of steps : "+str(step))
      break
    state=new_state
env.close()

****************************************************
EPISODE  0
  (Right)
SFFF
FHFH
FFFH
HFFG
number of steps : 11
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
number of steps : 8
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
number of steps : 16
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
number of steps : 55
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
number of steps : 21
****************************************************
EPISODE  5
  (Down)
SFFF
FHFH
FFFH
HFFG
number of steps : 36
****************************************************
EPISODE  6
  (Down)
SFFF
FHFH
FFFH
HFFG
number of steps : 43
****************************************************
EPISODE  7
  (Down)
SFFF
FHFH
FFFH
HFFG
number of steps : 46
****************************************************
EPISODE  8
  (Down)
SFFF
FHFH
FFFH
